export type BalochiAlphabetLetter = {
  letter: string
  name: string
}

export const BALOCHI_ALPHABET: BalochiAlphabetLetter[] = [
  { letter: 'ا', name: 'Aliph' },
  { letter: 'آ', name: 'Aliph madda' },
  { letter: 'ب', name: 'Bay' },
  { letter: 'پ', name: 'Pay' },
  { letter: 'ت', name: 'Tay' },
  { letter: 'ٹ', name: 'Ttay' },
  { letter: 'ث', name: 'Say' },
  { letter: 'ج', name: 'Jeem' },
  { letter: 'چ', name: 'Chay' },
  { letter: 'ح', name: 'Hay' },
  { letter: 'خ', name: 'Khay' },
  { letter: 'د', name: 'Dal' },
  { letter: 'ڈ', name: 'Ddal' },
  { letter: 'ذ', name: 'Zal' },
  { letter: 'ر', name: 'Ray' },
  { letter: 'ڑ', name: 'Rray' },
  { letter: 'ز', name: 'Zay' },
  { letter: 'ژ', name: 'Zhay' },
  { letter: 'س', name: 'Seen' },
  { letter: 'ش', name: 'Sheen' },
  { letter: 'ص', name: 'Suad' },
  { letter: 'ض', name: 'Zuad' },
  { letter: 'ط', name: 'Toay' },
  { letter: 'ظ', name: 'Zoay' },
  { letter: 'ع', name: 'Ain' },
  { letter: 'غ', name: 'Ghain' },
  { letter: 'ف', name: 'Fay' },
  { letter: 'ق', name: 'Qaf' },
  { letter: 'ک', name: 'Kaf' },
  { letter: 'گ', name: 'Gaf' },
  { letter: 'ل', name: 'Lam' },
  { letter: 'م', name: 'Meem' },
  { letter: 'ن', name: 'Noon' },
  { letter: 'ں', name: 'Noon ghunna' },
  { letter: 'و', name: 'Waw' },
  { letter: 'ہ', name: 'Hay do chashmi' },
  { letter: 'ھ', name: 'Do chashmi hay' },
  { letter: 'ء', name: 'Hamza' },
  { letter: 'ی', name: 'Choti yay' },
  { letter: 'ے', name: 'Bari yay' },
]
