// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitSearcher():Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<string>;
